### ISSUE TITLE
Atomic Grid Class

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#11]
`AtomicGridClass`:
1. Initialized with `RadilGrid` & `UnitSphereGrid` to generate points/weights.
2. Method to integrate.
3. Spherical averaging.

- Store pre-computed `tv-*.` in `json/yml` file.
- Have functions to load pre-computed points and return an instance of `AtomicGridClass`.

**Comment by tovrstra** [comment]
Initialization with a `RadialGrid` and a list of `UnitSphereGrid` objects (one for every point on the radial grid) is needed to support the built-in grids from HORTON2.

**Comment by FarnazH** [comment]
Have `get_spherical_decomposition` method? Just wanted to keep a note of it as it was removed in 76695ceaf27fa43e9b35cd768304cb8e4950a8b9.

**Comment by tovrstra** [comment]
This can still be useful, but it requires the `segments` feature in dot_multi. See #14.

**Comment by PaulWAyers** [comment]
This is the issue (closed; see also #14 ) related to the spherical averaging in AtomDB. 

It's good to be able to do a spherical harmonic/moment expansion around an arbitrary point. We can do this directly, but for atom-centered grids, it may be more efficient to leverage the spherical harmonic expansions we already have, then shift the center of the spherical harmonics. I can find a [Julia package](https://juliahub.com/ui/Packages/SphericalHarmonicExpansions/tAnO0/0.1.0#transformation-of-expansion-coefficients-under-translation) to do this, but no Python package. 

The formula is standard (reaturing Clebsch-Gordon coefficients or equivalent Wigner 3j). See [for example](https://link.springer.com/article/10.1134/S1995080218030022) but this is by no means the best reference, just the best one I could find quickly. A more classic references is from [Silverstone](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.16.1731).  I think a nice expression is in Jackson's Electromagnetism book, if I remember correctly. 

This is essentially the same as the need to shift moments from one origin to a new origin.
