### ISSUE TITLE
Molecular Grid Class

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#12]
- Have a pure Python implementation of Becke weights (just for the sake of having it)
- A function which takes all atomic numbers, all atomic coordinates, atomic grid points of one atom and it's an index to generate integration weights for that atom (i.e. something like Hirshfeld weights). These are called `aim_weights`.

`MolecularGrid` class:
1. Initialize with `aim_weights` & list of `AtomicGrid` instances. (Note: These weights are then multiplied by atomic weights to get the molecular integration weights.). It is probably better to store atomic number and coordinate of each atom in its `AtomicGrid` object.
2. Method for integration (inherited from base class).

**Comment by tovrstra** [comment]
Here is the reference to the SG1 paper: https://doi.org/10.1016/0009-2614(93)80125-9

**Comment by FarnazH** [comment]
For Lebedev grid stored in npz format, see 435231d75aa6f8ed7e4c1fb73ca3d72c3f679e07

**Comment by FarnazH** [comment]
SG1 should be implemented.

**Comment by FarnazH** [comment]
Update docstring of `lebedev` module to explain how Lebedev points/weights were generated. See https://github.com/theochem/grid/pull/111/commits/c42f2fa3325c99ed77990e73a36cd9dccd190b14

**Comment by FarnazH** [comment]
Similar to `AtomGrid` class, should we have a constructor for `MolGrid` to build predefined/pruned grids for the molecule?

**Comment by PaulWAyers** [comment]
Definitely. However I think we should have a high-level functionality that allows users to do it without passing in a radial grid, which is not very user-friendly. Usually the standard input is either a keyword (pruned grid) or a radial+angular specification. The latter allows one finer control over accuracy at the loss of efficiency.
