### ISSUE TITLE
Error for some onedgrid/transform combinations

### ISSUE THREAD

**Issue by leila-pujal** [theochem/grid#132]
I was combining some onedgrid and transformation and I came accross with an error that I am not sure if it is a bug or if this is the intended behaviour of the code. 

I combined the following `oned` grid and `rtransform`:
```
oned = Trapezoidal(22)
grid = BeckeTF(1e-4, 1.5).transform_1d_grid(oned) 
```

and I got the following error:
```
Traceback (most recent call last):
  File "test_from_predefined.py", line 36, in <module>
    rgrid = MultiExpTF(1e-6, 1.30).transform_1d_grid(oned) #BeckeTF(rmin, rmax)
  File "/home/leila/grid/grid/src/grid/rtransform.py", line 101, in transform_1d_grid
    return OneDGrid(new_points, new_weights, new_domain)
  File "/home/leila/grid/grid/src/grid/basegrid.py", line 272, in __init__
    f"point coordinates should not be above domain! {domain[1] < max_p}"
ValueError: point coordinates should not be above domain! False
```

I looked a little into this and this is what I understood. `Trapezoidal` one d grid has a domain=[-1,1], including -1 and 1, meaning the minimum and maximum points generated are -1 and 1. When the transformation is applied, -1 and 1 will be equal to the lower and upper domain values of the transform. In the case of `BeckeTF` domain is [r_min, inf], thus point with value -1 before transform = rmin and point with value 1 before transform = inf, but this value is trimmed so it will be equal to 1e16 instead of inf, after the transformation is applied. After obtaining this new values of the points, the code creates a new `OneDGrid` in `basegrid.py` and it goes through the several checks comparing the new points and the new domain. For the lowest point there's no problem but for the highest, 1e16 in this case, this line is what gives the error:
https://github.com/theochem/grid/blob/d3d0590ad6f82c926cf6ef68349a6dd3ea204d1e/src/grid/basegrid.py#L266

I am not sure about the purpose of the 1e-7 summation to the domain, but it is clear that by deleting the equal comparison this issue is solved, but as I said, I am not sure if this is a correct error detection.  I checked all types of onedgrids and the two that gave this error are `Trapezoidal` and `GaussChebyshevLobatto`. 

Let me know if something is unclear about the explanation or that if something that I wrote is wrong.

**Comment by PaulWAyers** [comment]
In trapezoidal and Gauss-Chebyshev-Lobotto (and perhaps others) there are points that are *exactly* at -1 and +1. The +1 point can be removed (the integrand is *always* zero there) but the -1 point maps directly onto zero. It should be allowed to be exactly zero if rmin = 0.0, but otherwise rmin I think. I'm not sure why this was done; there should have been a comment at least....
