### ISSUE TITLE
dot_multi rewritten 

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/grid#14]
Something to reproduce the dot_multi functionality in the old grid code. This is a big win computationally....

@tovrstra has some ideas about how this could be done.  There would be a nice functionality in qcgrid for this but probably a bare-bones Python implementation for grid would be useful.

**Comment by tovrstra** [comment]
`np.einsum` can handle this well.

**Comment by FarnazH** [comment]
@tovrstra do we need `segments` option in `dot_multi`?

**Comment by tovrstra** [comment]
I'm not sure. This feature was used for efficiently computing spherical averages.

**Comment by tovrstra** [comment]
Oh, and it was also used for spherical decomposition, where the radial part is kept on a grid.

**Comment by PaulWAyers** [comment]
I'm not sure what the `segments` was used for. In my notes I do mention being able to use partial grids for things, and the spherical decomposition. I talked to Derrick a bit about this today...I guess maybe the key is to just go as we were, and we can refactor as needed later.
