### ISSUE TITLE
Cannot use outside of grid directory

### ISSUE THREAD

**Issue by khuddzu** [theochem/grid#151]
Hi, 
I might just be missing something. 
However I cannot import this package in my code. It tells me the module does not exist. 

"""
ModuleNotFoundError: No module named 'grid'
"""

To install I did the following:

"""
git clone {ssh address}

in initial directory: pip install -e .
"""

I also added an __init__.py file in the initial directory, to see if that would be a fix, and it was not 

I cannot pip install in the grid/src/grid directory because there is no setup.py

When I install it says this: 

"""
 Running setup.py develop for grid
Successfully installed grid-0.0.0
"""
Is the 0.0.0 an issue? 

Here are the imports I have tried:
"""
import grid
from src import grid
from grid.src import grid
"""

All with the same result. The module cannot be found. 

Thank you!

Kate

**Comment by tczorro** [comment]
Hi Kate, running `pip install -e .` along should be enough to install the package.  My guess is the `python` you use to `import grid` is in the different environment as the `pip`. I would recommend you to run `which python` and `which pip` in the terminal and check both are in the same environment.

**Comment by khuddzu** [comment]
Thanks for the response!
They are in the same location.

**Comment by PaulWAyers** [comment]
@khuddzu so it is working now? If so, please close the issue. If not, Ramon Miranda (@ramirandaq) and David (Taewon) Kim (@kimt33) are at UF and could perhaps help.

**Comment by FarnazH** [comment]
@khuddzu, is your problem fixed? If not, please let us and we can arrange to meet to have it fixed.

**Comment by khuddzu** [comment]
Sorry for delaying you. I still could not figure it out. None the less, I do not need it anymore. Thanks
