### ISSUE TITLE
Angular Grid Docstring Formula

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#232]
@Ali-Tehrani, based on https://github.com/theochem/grid/blob/master/src/grid/angular.py#L387, shouldn't we add a :math:`4\pi` to the integral given in https://github.com/theochem/grid/blob/master/src/grid/angular.py#L291? Let me know your thoughts.

**Comment by Ali-Tehrani** [comment]
I don't believe so, the 4pi is a result of how Lebedev quadrature is done and was a chosen convention.  [Wikipedia](https://en.wikipedia.org/wiki/Lebedev_quadrature) has a good explanation on it.

**Comment by FarnazH** [comment]
@Ali-Tehrani, that's exactly what I was thinking about. To add the $4\pi$ in the formula like the Wikipedia. To make things simpler, I just added a clarification here: [164b258](https://github.com/theochem/grid/pull/239/commits/164b2585e846a0410def31e6b73e1ba589699df0)
Let me know if you have a comment.

**Comment by Ali-Tehrani** [comment]
Ah I see, thanks! Forgot to include that in the angular docstring
