### ISSUE TITLE
Link Website's API to GitHub's Source Code

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#250]
Clicking on the link sign denoted below does not open the source code page on GitHub. 

<img width="1727" alt="Screenshot 2024-05-12 at 1 12 39 PM" src="https://github.com/theochem/grid/assets/4535622/870e45c6-de7b-4c50-944c-f850947b5f85">

**Comment by Ali-Tehrani** [comment]
This is solved and I verified it on the github page. I'll close this issue as I don't think anything new problems should occur.
