### ISSUE TITLE
Some tricks for spherical harmonics that might be useful

### ISSUE THREAD

**Issue by tovrstra** [theochem/grid#66]
This is not urgent, just posting it here to keep track.

The following code can probably be converted to python and with vectorization tricks it should not be too slow: https://github.com/theochem/horton/blob/master/horton/moments.cpp#L59 It computes the real solid spherical harmonics, given Cartesian coordinates. This way one can avoid the series of conversions currently used: Cartesian -> phi, theta -> complex harmonics -> real harmonics.

**Comment by PaulWAyers** [comment]
I think we have an explicit cartesian -> spherical and spherical -> cartesian in `gbasis` too. If not there are explicit formulas for these which I think can be used (to arbitrary order). My internet is dodgy right now so I didn't investigate if this is equivalent to what is in moments.cpp

**Comment by wilhadams** [comment]
`gbasis` has real solid spherical harmonics here: https://github.com/theochem/gbasis/blob/master/gbasis/spherical.py#L165

**Comment by PaulWAyers** [comment]
@tovrstra  is the issue here computing multipole moments for an arbitrary center? We have interpolation and Poisson-solving using spherical harmonics *around* an atomic center (for Becke-Lebedev-style grids). But for computing arbitrary multipole moments around arbitrary centers, we would want/need something like this.

**Comment by tovrstra** [comment]
Evaluating moments is one use case. Also for a (numerically stable & efficient) decomposition of any 3D function into a basis of "(real sphercal harmonics) x ( radial function on a grid)", this is needed.

I don't think the choice of the center is special. The code we had in HORTON2 took an array with positions relative to a center and the maximum angular moment as input, and then recursively computed all real solid spherical harmonics up to the maximum angular momentum. This can be made numerically stable and intermediate results can be reused for efficiency. Once you have these functions on a set of grid points, they can be used for various purposes, e.g. computing multipole moments.

**Comment by tovrstra** [comment]
It would be good to check numerical stability for points close to the poles of a sphere. (It may be ok.) Recursive algorithms, which work directly in Cartesian coordinates without computing phi and theta, tend to be numerically stable and can be very efficient when computing all spherical harmonics up to a high angular momenta. If the main advantage is just efficiency, this issue can be deferred.

**Comment by PaulWAyers** [comment]
Dealt with by PR #155 .

This directly computes spherical moments using recursive implementation of the spherical harmonics. While evaluating spherical harmonics on a grid is slower than evaluating Cartesian powers, for high orders, the number of spherical moments is much less ($~2 \ell + 1$ vs $~\ell^2 $
