### ISSUE TITLE
preloading can be made a bit more efficient

### ISSUE THREAD

**Issue by tovrstra** [theochem/grid#67]
At the moment, pre-loading of lebedev grids is done inside the `AtomicGrid` class, meaning that it gets repeated for every atom, if I understand correctly (should be tested). It can also be implemented in the lebedev.py module, such that preloaded grids stay in memory until the process ends. (The memory overhead is very small.)

**Comment by tczorro** [comment]
Add global cache variable to store all loaded `lebedev` grid for fast I/O
